// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdwucvnbhfzmqenfuxnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkd3Vjdm5iaGZ6bXFlbmZ1eG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzMxNTYsImV4cCI6MjA2NDQ0OTE1Nn0.uNCmB7hOff46HwaUh7kvzHlbFRGXZcPIry3mpIyT4mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);