// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plrhjvcmeabypeukiptm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscmhqdmNtZWFieXBldWtpcHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTczNTgsImV4cCI6MjA2NzYzMzM1OH0.1QLYY7-hU6HaAojNz1End3pjiaHeeBlZ4mWTyuqcFko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);